# The URL the site will be built for
base_url = "https://spiss.dev"
theme = "tabi-local"
title = "spiss.dev"
description = "Lukas Spiss - personal page and blog."
author = "spissable"
generate_feeds = true
compile_sass = true
minify_html = true
build_search_index = false

[markdown]
highlight_code = true

[extra]
favicon = "/favicon.ico"

full_content_in_feed = true

skin = "blue"

copy_button = true

menu = [
    { name = "blog", url = "blog", trailing_slash = true },
    { name = "about", url = "about", trailing_slash = true },
]
feed_icon = true

email = "lukas@spiss.dev"

socials = [
    { name = "github", url = "https://github.com/spissable/", icon = "github" },
    { name = "linkedin", url = "https://www.linkedin.com/in/lukas-spiss/", icon = "linkedin" },
    { name = "instagram", url = "https://instagram.com/spisslukas", icon = "instagram" },
]

allowed_domains = [
    { directive = "font-src", domains = ["'self'", "spiss.dev", "*.spiss.dev", "data:"] },
    { directive = "img-src", domains = ["'self'", "https://*", "data:"] },
    { directive = "media-src", domains = ["'self'", "spiss.dev", "*.spiss.dev"] },
    { directive = "script-src", domains = ["'self'", "spiss.dev", "*.spiss.dev"] },
    { directive = "style-src", domains = ["'self'", "spiss.dev", "*.spiss.dev"] },
    { directive = "frame-src", domains = ["'self'", "spiss.dev", "*.spiss.dev"] },
]
